// Baked-in build metadata (release pipeline sets APP_VERSION / APP_GIT_SHA as
// build-args; `cargo:rustc-env` exposes them to the binary via env!()).
// Also generated by `sqlx migrate build-script`.
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=db/migrations/");

    for var in ["APP_VERSION", "APP_GIT_SHA"] {
        match std::env::var(var) {
            Ok(value) => println!("cargo:rustc-env={var}={value}"),
            // Default to an empty value for local builds without build-args
            // (the `=` is required even for empty values).
            Err(_) => println!("cargo:rustc-env={var}="),
        }
    }
    println!("cargo:rerun-if-env-changed=APP_VERSION");
    println!("cargo:rerun-if-env-changed=APP_GIT_SHA");
}